"""Subclass of MyWindow1, which is generated by wxFormBuilder."""

import wx
import Windows1

# Implementing MyWindow1
class WXFenster1MyWindow1( Windows1.MyWindow1 ):
	def __init__( self, parent ):
		Windows1.MyWindow1.__init__( self, parent )

	# Handlers for MyWindow1 events.
	def OnBtnSaveClicked( self, event ):
		# TODO: Implement OnBtnSaveClicked
		pass

	def OnBtnCancelClicked( self, event ):
		# TODO: Implement OnBtnCancelClicked
		pass


